---
- name: configure jenkins-master
  hosts: jenkins-master
  remote_user: vagrant
  become: yes
  become_method: sudo
  
  tasks:
  - name: install wget
    yum: name=wget state=latest
  - name: download java
    command: "wget --no-cookies --no-check-certificate --header 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie' 'http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jdk-8u45-linux-x64.rpm'"