---
- name: configure jenkins-master
  hosts: jenkins-master
  remote_user: vagrant
  become: yes
  become_method: sudo
  
  tasks:
  - name: test connection
    ping:
  - name: install vim
    yum: name=vim state=latest
  - name: download jenkins
    get_url: 
      url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  - name: update jenkins rpm
    rpm_key:  
      key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
  - name: install jenkins
    yum: name=jenkins state=latest
  - name: start jenkins
    service: name=jenkins state=started